### ISSUE TITLE
Char and Varchar's length limit not respected

### ISSUE THREAD

**Issue by xxchan** [risinglightdb/risinglight#455]
Secondary engine 
```
> create table c (x char(3) not null);
created
> insert into c values ('111')
1 rows inserted
> insert into c values ('1111')
thread 'main' panicked at 'item length 4 > char width 3', src/storage/secondary/block/char_block_builder.rs:39:13

> create table cc (x varchar(3) not null)
created
> insert into cc values ('1111')
1 rows inserted
```

https://github.com/risinglightdb/risinglight/blob/c221b085ceb4a61fe1cf1e6c9d6caa36b7215a2e/src/storage/secondary/column/column_builder.rs#L44

Because varchar has a length limit...

---

memory engine has no check at all
```
> create table cc (x char(3) not null)
created
> insert into cc values ('1111')
1 rows inserted
```

**Comment by skyzh** [comment]
I'm thinking whether we need this check at all... From the storage part, the layout supports variable length, regardless of how logical type is being set.

Maybe we should do this check at `InsertExecutor` or `ValuesExecutor`?

**Comment by xxchan** [comment]
Yes I also think it is better to perform check above storage layer

**Comment by xiaoyong-z** [comment]
i will take this.

**Comment by RinChanNOWWW** [comment]
I have a question about the Char type. If I create char type column without `not null`, I can't insert anything.

```
> create table t (col char(5));
created  
in 0.038s
> insert into t values('a');
thread 'tokio-runtime-worker' panicked at 'not implemented: width Some(5) with nullable true not implemented', src/storage/secondary/column/char_column_builder.rs:127:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-02-26T08:05:33.943527Z  WARN risinglight::storage::secondary::transaction: Transaction dropped without committing or aborting
thread 'tokio-runtime-worker' panicked at 'failed to join insert thread: JoinError::Panic(...)', src/executor/insert.rs:63:41
thread 'main' panicked at 'failed to join query thread: JoinError::Panic(...)', src/main.rs:106:23
```

Is this behavior correct?

**Comment by RinChanNOWWW** [comment]
> As the message indicates, it is just not implemented yet…
> 
> If you are intersted, you can try to implement it!

`manifest.json` after `create table t (col char(5));`:

```json
 {
    "CreateTable": {
        "database_id": 0,
        "schema_id": 0,
        "table_name": "t",
        "column_descs": [
            {
                "id": 0,
                "desc": {
                    "datatype": {
                        "kind": {
                            "Char": 10
                        },
                        "physical_kind": "String",
                        "nullable": true
                    },
                    "name": "a",
                    "is_primary": false
                }
            }
        ]
    }
}
```

It shows that the `nullable` field is set to `true` as deafult. I'm wondering if this is a bug.

**Comment by skyzh** [comment]
Nullable encoding for fixed length char is not implemented yet. If you are interested in this, you may create a separate issue and send a PR.
