### ISSUE TITLE
executor: support delete full table

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#494]
```
> delete from test2;
thread 'tokio-runtime-worker' panicked at 'delete whole table is not supported yet', src/logical_planner/delete.rs:17:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'failed to join query thread: JoinError::Panic(...)', src/main.rs:79:23
```

We already support `delete from table where true`, so we can easily support delete full table.

**Comment by skyzh** [comment]
resolved in https://github.com/risinglightdb/risinglight/pull/511
